[hero]
title="EPILEPSIA"
subtitle="Algo así era"

[about]
title="SOBRE NOSOTROS"
content="La epilepsia es una enfermedad provocada por un desequilibrio en la actividad eléctrica de las neuronas de alguna zona del cerebro. Se caracteriza por uno o varios trastornos neurológicos que dejan una predisposición en el cerebro a padecer convulsiones recurrentes, que suelen dar lugar a consecuencias neurobiológicas, cognitivas y psicológicas."

[portfolio]
title="PORTAFOLIO"

[contact]
title="CONTACT"