#[template]
#title=
#description=
#releaseDate=
#coverName=
#type=
#link=
#sheet=

[expiacion]
title="Expiación"
description="Arthur, un viejo y solitario hombre, sigue los pasos de un antiguo ritual judío, para poder expiar sus pecados y salvar su alma."
releaseDate="2023"
coverName="Expiación Poster.png"
type="CORTOMETRAJE"
link="https://youtu.be/UdDZ4oUrZXM"
sheet=[
["Dirección", "Joaquín Ralph y Franco Padin"],
["Guión", "Franco Padin"],
["Dirección de Fotografía", "Joaquín Ralph"],
["Gaffer", "Sofía Cappetto"],
["Dirección de Arte", "Fernando Torres e Irina González"],
["Dirección de Sonido", "Jessica Fernández"],
["Micrófono", "Juan Manuel Gómez"],
["Banda Sonora", "Francisco Mejide"],
["Diseño Sonoro", "Francisco Mejide"],
["Montaje", "Joaquín Ralph y Franco Padin"],
["Actuación", "Lionel Sinnott"],
]

[eden]
title="Edén"
description="Un joven sumido en la monotonía del día a día, atormentado por sus pensamientos intrusivos y la profunda angustia, decide quitarse la vida frente a su unico compañero; un viejo televisor. Sin quererlo, crea una irremediable conexión con un paraíso siniestro."
releaseDate="2023"
coverName="Edensolo.png"
type="CORTOMETRAJE"
link="https://vimeo.com/918038415"
sheet=[
["Dirección", "Jessica Fernández, Franco Padin y Ignacio Ramallo"],
["Asistencia de Dirección", "Franco Padin"],
["Dirección de Fotografía", "Joaquín Ralph y Sofía Cappetto"],
["Dirección de Arte", "Fernando Torres e Irina González"],
["Dirección de Sonido", "Agustín Candal"],
["Montaje", "Joaquín Ralph, Franco Padin y Ignacio Ramallo"],
["Actuación", "Ignacio Ramallo, Jessica Fernández y Fernando Torres"],
]

[katalepsis]
title="Katálēpsis"
description="La noche se convierte en un purgatorio sin fin que trae consigo el pasado pecaminoso de un hombre que ahora huye de los lúgubres y lívidos recuerdos que se encarnan en el espectro de una mujer."
releaseDate="2023"
coverName="Katalepsis Final.png"
type="CORTOMETRAJE"
link="https://vimeo.com/819819044"
sheet=[
["Dirección", "Ignacio Ramallo"],
["Asistencia de Dirección", "Franco Padin"],
["Dirección de Fotografía", "Joaquín Ralph"],
["Dirección de Arte", "Irina González"],
["Dirección de Sonido", "Juan Manuel Gómez"],
["Montaje", "Ignacio Ramallo"],
["Actuación", "Ignacio Ramallo y Jessica Fernández"],
]
