#[template]
#title=
#description=
#releaseDate=
#coverName=
#type=
#link=

[terminator]
title="Expiación"
description="Arthur, un viejo y solitario hombre, sigue los pasos de un antiguo ritual judío, para poder expiar sus pecados y salvar su alma."
releaseDate="2023"
coverName="Expiación Poster.png"
type="CORTOMETRAJE"
link="https://vimeo.com/940848616"

[terminator2]
title="Terminator 2: Judgement Day"
description="A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten year old son John from an even more advanced and powerful cyborg."
releaseDate="1991"
coverName="terminator2.jpg"
type="LARGOMETRAJE"
link="https://vimeo.com/918038415"

[sharknado]
title="Sharknado"
description="La mejor película de la historia."
releaseDate="2013"
coverName="sharknado.jpg"
type="LARGOMETRAJE"
link="https://vimeo.com/819819044"
